---
title: "Figure DA"
author: "Rebecca Ansorge"
date: "31/03/2023"
output: html_document
---

# Make DA figure

## Load libraries 
```{r}
library(tidyverse)
library(RColorBrewer)
library(ggtree)
library(ape)
library(ggtreeExtra)
library(pheatmap)
library(ggnewscale)
library(formattable)
library(gridExtra)
library(cowplot)

```

## Load data

```{r}
#PATHanalNov2023<-"~/Documents/Rebecca/onedrive/analysisNov2023/"
PATHanalNov2023<-"~/Documents/Rebecca/onedrive/analysisNov2023/"
PATH<-"~/Documents/Rebecca/onedrive/submission/natcom/revision/checks/"
q<-0.1
```

```{r}
# define color palette

#col_IBD2<-c("#E8A400","#E31A1C","#FB9A99","#1F78B4","#1F78B4","#1F78B4", "grey40","#E8A400")
col_IBD2<-c("gold2","#E31A1C","darkorange","#1F78B4","#1F78B4","#1F78B4", "grey40","#E8A400")
names(col_IBD2)<-c("IBD","CD","UC","healthy","control", "Healthy","variable","disease")

col_IBD3<-c("#1F78B4","#1F78B488","#1F78B466","#1F78B433","#E8A400","#E8A40088","#E8A40066","#E8A40033")
names(col_IBD3)<-c("control_robust","control_variableCD","control_variableUC","control_variable","disease_robust","disease_variableCD","disease_variableUC","disease_variable")


phyCol.df<-data.frame(Phylum=c("Firmicutes_A","Firmicutes_B","Firmicutes_C","Firmicutes_G","Firmicutes","Bacteroidota","Verrucomicrobiota","Proteobacteria","Desulfobacterota_I","Campylobacterota","Fusobacteriota","Cyanobacteria","Synergistota","Actinobacteriota","Thermoplasmatota","Methanobacteriota"),PhylumColor=c("darkgreen","green4","green3","green1","lightgreen","black","purple4","steelblue4","grey","red3","#4900FF","orchid3", "skyblue1","goldenrod2" ,"yellow3", "chocolate2")) ### RAN CHECK THIS
phy.col<-phyCol.df$PhylumColor
names(phy.col)<-phyCol.df$Phylum

#display.brewer.pal(n=12, name="Paired")
#brewer.pal(n=12, name="Paired")
```

### Import correlation df
```{r}
df_cor_all_DAibd_all_sigs<-readRDS(paste0(PATHanalNov2023,"humanReads/MGScorvsDAibd.crosslong.q0.1.rds")) # change 
df_cor_all_DAibd_all_sigs_IBD<-readRDS(paste0(PATHanalNov2023,"humanReads/MGScorvsDAibd.crosslong.IBDonly.q0.1.rds"))
df_cor_all_DAibd_all_sigs_CTRL<-readRDS(paste0(PATHanalNov2023,"humanReads/MGScorvsDAibd.crosslong.CTRLonly.q0.1.rds"))
MGScor_blInd_DA_gat<-readRDS(paste0(PATHanalNov2023,"humanReads/MGScor_blInd_DA_gat.q0.1.rds"))%>%
  separate(MGS, into = c('Kingdom', 'Phylum', 'Class', 'Order', 'Family','Genus', 'Species','MGS'), sep=";")
```

### IBD-HC
```{r}
# all species DA
metaDA<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.prevfilt.rds"))
# robust species DA
metaDAsig<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.prevfilt.sign0.1.rds"))
# robust species DA
metaDArobust<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.prevfilt.sign0.1.20.rds"))
#robustMGSda<-metaDArobust[[1]][,"bins"] # get IDs of robust MGS

# use dplyr to count number of times MGS was significant
metaDAsigall<-do.call(rbind, metaDAsig)
robustMGSda<-unique((metaDAsigall%>%count(bins)%>%filter(n==20))[["bins"]])
variableMGSda<-unique((metaDAsigall%>%count(bins)%>%filter(n<20))[["bins"]])

DAmeans<-do.call(rbind, metaDA)
DAmeans<-DAmeans%>%
  mutate(robustDA=ifelse(bins%in%robustMGSda,"robust",ifelse(bins%in%variableMGSda,"variable","non-sig")))%>%
  group_by(bins)%>%
  mutate(TE.random=as.numeric(TE.random)) %>% ### added this
  mutate(meanTE=mean(TE.random, na.rm=TRUE))%>%
  mutate(stdevTE=sd(TE.random, na.rm=TRUE))%>%
  select(c(bins,meanTE,stdevTE,robustDA))%>%
  distinct()%>%
  rename(MGS=bins)%>% 
  mutate(comparison="IBD-HC")%>%
  mutate(meanTE=-meanTE) # invert direction to make enrichment in HC positive


Top20<-(DAmeans%>%
  filter(robustDA=="robust")%>%
  arrange(abs(meanTE))%>%
  tail(20))$MGS
```

### CD-HC
```{r}
# all species DA
metaDA.cdhc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.cdhc.prevfilt.rds"))
# robust species DA
metaDAsig.cdhc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.cdhc.prevfilt.sign0.1.rds"))
# significant species DA
metaDArobust.cdhc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.cdhc.prevfilt.sign0.1.20.rds"))
#robustMGSda.cdhc<-metaDArobust.cdhc[[1]][,"bins"] # get IDs of robust MGS

# use dplyr to count number of times MGS was significant
metaDAsigall.cdhc<-do.call(rbind, metaDAsig.cdhc)
robustMGSda.cdhc<-unique((metaDAsigall.cdhc%>%count(bins)%>%filter(n==20))[["bins"]])
variableMGSda.cdhc<-unique((metaDAsigall.cdhc%>%count(bins)%>%filter(n<20))[["bins"]])

DAmeans.cdhc<-do.call(rbind, metaDA.cdhc)
DAmeans.cdhc<-DAmeans.cdhc%>%
  mutate(robustDA=ifelse(bins%in%robustMGSda.cdhc,"robust",ifelse(bins%in%variableMGSda.cdhc,"variable","non-sig")))%>%
  group_by(bins)%>%
  mutate(TE.random=as.numeric(TE.random)) %>% ### added this
  mutate(meanTE=mean(TE.random, na.rm=TRUE))%>%
  mutate(stdevTE=sd(TE.random, na.rm=TRUE))%>%
  select(c(bins,meanTE,stdevTE,robustDA))%>%
  distinct()%>%
  rename(MGS=bins)%>%
  mutate(comparison="CD-HC")

Top20.cdhc<-(DAmeans.cdhc%>%
  filter(robustDA=="robust")%>%
  arrange(abs(meanTE))%>%
  tail(20))$MGS
```

### UC-HC
```{r}
# all species DA
metaDA.uchc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.uchc.prevfilt.rds"))
# robust species DA
metaDAsig.uchc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.uchc.prevfilt.sign0.1.rds"))
# robust species DA
metaDArobust.uchc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.uchc.prevfilt.sign0.1.20.rds"))
#robustMGSda.uchc<-metaDArobust.uchc[[1]][,"bins"] # get IDs of robust MGS

# use dplyr to count number of times MGS was significant
metaDAsigall.uchc<-do.call(rbind, metaDAsig.uchc)
robustMGSda.uchc<-unique((metaDAsigall.uchc%>%count(bins)%>%filter(n==20))[["bins"]])
variableMGSda.uchc<-unique((metaDAsigall.uchc%>%count(bins)%>%filter(n<20))[["bins"]])

DAmeans.uchc<-do.call(rbind, metaDA.uchc)
DAmeans.uchc<-DAmeans.uchc%>%
  mutate(robustDA=ifelse(bins%in%robustMGSda.uchc,"robust",ifelse(bins%in%variableMGSda.uchc,"variable","non-sig")))%>%
  group_by(bins)%>%
  mutate(TE.random=as.numeric(TE.random)) %>% ### added this
  mutate(meanTE=mean(TE.random, na.rm=TRUE))%>%
  mutate(stdevTE=sd(TE.random, na.rm=TRUE))%>%
  select(c(bins,meanTE,stdevTE,robustDA))%>%
  distinct()%>%
  rename(MGS=bins)%>%
  mutate(comparison="UC-HC")

Top20.uchc<-(DAmeans.uchc%>%
  filter(robustDA=="robust")%>%
  arrange(abs(meanTE))%>%
  tail(20))$MGS
```

### CD-UC
```{r}
# all species DA
metaDA.cduc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.cduc.prevfilt.rds"))
# robust species DA
metaDAsig.cduc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.cduc.prevfilt.sign0.1.rds"))
# robust species DA
metaDArobust.cduc<-readRDS(paste0(PATHanalNov2023,"DA_analysis/November_2023_v3/R_analysis/RDS/l.meta.cduc.prevfilt.sign0.1.20.rds"))
#robustMGSda.cduc<-metaDArobust.cduc[[1]][,"bins"] # get IDs of robust MGS

# use dplyr to count number of times MGS was significant
metaDAsigall.cduc<-do.call(rbind, metaDAsig.cduc)
robustMGSda.cduc<-unique((metaDAsigall.cduc%>%count(bins)%>%filter(n==20))[["bins"]])
variableMGSda.cduc<-unique((metaDAsigall.cduc%>%count(bins)%>%filter(n<20))[["bins"]])

DAmeans.cduc<-do.call(rbind, metaDA.cduc)
DAmeans.cduc<-DAmeans.cduc%>%
  mutate(robustDA=ifelse(bins%in%robustMGSda.cduc,"robust",ifelse(bins%in%variableMGSda.cduc,"variable","non-sig")))%>%
  group_by(bins)%>%
  mutate(TE.random=as.numeric(TE.random)) %>% ### added this
  mutate(meanTE=mean(TE.random, na.rm=TRUE))%>%
  mutate(stdevTE=sd(TE.random, na.rm=TRUE))%>%
  select(c(bins,meanTE,stdevTE,robustDA))%>%
  distinct()%>%
  rename(MGS=bins)%>%
  mutate(comparison="CD-UC")

Top20.cduc<-(DAmeans.cduc%>%
  filter(robustDA=="robust")%>%
  arrange(abs(meanTE))%>%
  tail(20))$MGS


```


```{r}
# export DA tables
write.table(DAmeans,paste0(PATHanalNov2023,"Downstream/Results/DAmeans.IBDHC.0.1.txt"),sep="\t",row.names=FALSE)
write.table(DAmeans.cdhc,paste0(PATHanalNov2023,"Downstream/Results/DAmeans.CDHC.0.1.txt"),sep="\t",row.names=FALSE)
write.table(DAmeans.uchc,paste0(PATHanalNov2023,"Downstream/Results/DAmeans.UCHC.0.1.txt"),sep="\t",row.names=FALSE)
write.table(DAmeans.cduc,paste0(PATHanalNov2023,"Downstream/Results/DAmeans.CDUC.0.1.txt"),sep="\t",row.names=FALSE)

DAmeans.all.mod<-DAmeans%>%
  full_join(DAmeans.cdhc,by="MGS")%>%
  full_join(DAmeans.uchc,by="MGS")%>%
  full_join(DAmeans.cduc,by="MGS")%>%
  select(-c(5,9,13,17))
colnames(DAmeans.all.mod)<-c("MGS","meanTE.IBDHC","stdevTE.IBDHC","IBDHC","meanTE.CDHC","stdevTE.CDHC","CDHC","meanTE.UCHC","stdevTE.UCHC","UCHC","meanTE.CDUC","stdevTE.CDUC","CDUC")
write.table(DAmeans.all.mod,paste0(PATHanalNov2023,"Downstream/Results/DAmeans.ALL.0.1.txt"),sep="\t",row.names=FALSE)

IBDHCdis<-DAmeans.all.mod%>%filter(meanTE.IBDHC<0)%>%filter(IBDHC!="non-sig")%>%group_by(IBDHC)%>%count
CDHCdis<-DAmeans.all.mod%>%filter(meanTE.CDHC<0)%>%filter(CDHC!="non-sig")%>%group_by(CDHC)%>%count
UCHCdis<-DAmeans.all.mod%>%filter(meanTE.UCHC<0)%>%filter(UCHC!="non-sig")%>%group_by(UCHC)%>%count
CDUCdis<-DAmeans.all.mod%>%filter(meanTE.CDUC<0)%>%filter(CDUC!="non-sig")%>%group_by(CDUC)%>%count

IBDHCctrl<-DAmeans.all.mod%>%filter(meanTE.IBDHC>0)%>%filter(IBDHC!="non-sig")%>%group_by(IBDHC)%>%count
CDHCctrl<-DAmeans.all.mod%>%filter(meanTE.CDHC>0)%>%filter(CDHC!="non-sig")%>%group_by(CDHC)%>%count
UCHCctrl<-DAmeans.all.mod%>%filter(meanTE.UCHC>0)%>%filter(UCHC!="non-sig")%>%group_by(UCHC)%>%count
CDUCctrl<-DAmeans.all.mod%>%filter(meanTE.CDUC>0)%>%filter(CDUC!="non-sig")%>%group_by(CDUC)%>%count


DA.num.overview<-data.frame(
  enriched=c("disease","disease","control","control"),
  DA=c("robust","variable","robust","variable"),
  IBDHC=c(IBDHCdis$n,IBDHCctrl$n),
  CDHC=c(CDHCdis$n,CDHCctrl$n),
  UCHC=c(UCHCdis$n,UCHCctrl$n),
  CDUC=c(CDUCdis$n,CDUCctrl$n)
)

write.table(DA.num.overview,paste0(PATHanalNov2023,"Downstream/Results/DA.num.overview.0.1.txt"),sep="\t",row.names=FALSE)
DA.num.overview
```


```{r}
# metadata
ibdMeta<-read.delim2(paste0(PATHanalNov2023,"PrepData/IBDmeta.cur.filt.mc.matched.txt"), sep="\t") %>%
  mutate(row=SmplID) %>%
  column_to_rownames("row")

# taxonomy
MGStax<-read.delim2(paste0(PATHanalNov2023,"PrepData/IBD.MGStaxa.txt"), sep="\t")

# MGS tree
spTree<-read.tree(paste0(PATHanalNov2023,"PrepData/IQtree_allsites.treefile"))
```

## combine l.meta runs
```{r}
# get 20 most strongly altered for all comparisons
topMGSall<-unique(sort(c(Top20,Top20.cdhc,Top20.cduc,Top20.uchc)))
length(topMGSall)

DAmeans.all<-rbind(DAmeans,DAmeans.cdhc,DAmeans.uchc,DAmeans.cduc)

DAmeans.topMGS<-DAmeans.all%>%filter(MGS%in%topMGSall)
```

```{r fig.width=3, fig.height=3}

DAmeans.all.mod_overlap<-DAmeans.all.mod%>%
  ungroup()%>%
  mutate(enrichedIn.IBDHC=ifelse(IBDHC=="non-sig","non-sig",ifelse(meanTE.IBDHC>0,"control","disease")))%>%
  mutate(enrichedIn.CDHC=ifelse(CDHC=="non-sig","non-sig",ifelse(meanTE.CDHC>0,"control","disease")))%>%
  mutate(enrichedIn.UCHC=ifelse(UCHC=="non-sig","non-sig",ifelse(meanTE.UCHC>0,"control","disease")))%>%
  mutate(enrichedIn.CDUC=ifelse(CDUC=="non-sig","non-sig",ifelse(meanTE.CDUC>0,"UC","CD")))

missing_mgs.cdhc<-(DAmeans.all.mod_overlap%>%filter(is.na(enrichedIn.CDHC)))$MGS
missing_mgs.uchc<-(DAmeans.all.mod_overlap%>%filter(is.na(enrichedIn.UCHC)))$MGS
missing_mgs.cduc<-(DAmeans.all.mod_overlap%>%filter(is.na(enrichedIn.CDUC)))$MGS


missing_mgs.cdhc.df<-metaDAsigall.cdhc%>%
  filter(bins%in%missing_mgs.cdhc)%>%
  distinct(bins, .keep_all = TRUE)%>%
  mutate(enrichedIn.CDHC=ifelse(TE.random>0,"control","disease"))

missing_mgs.uchc.df<-metaDAsigall.uchc%>%
  filter(bins%in%missing_mgs.uchc)%>%
  distinct(bins, .keep_all = TRUE)%>%
  mutate(enrichedIn.UCHC=ifelse(TE.random>0,"control","disease"))

missing_mgs.cduc.df<-metaDAsigall.cduc%>%
  filter(bins%in%missing_mgs.cduc)%>%
  distinct(bins, .keep_all = TRUE)%>%
  mutate(enrichedIn.CDUC=ifelse(TE.random>0,"UC","CD"))

DAmeans.all.mod_overlap<-DAmeans.all.mod_overlap %>%
    left_join(missing_mgs.cdhc.df[,c(6,8)], by = c('MGS'='bins'), suffix = c('', '.y')) %>%
    mutate(enrichedIn.CDHC = coalesce(enrichedIn.CDHC, enrichedIn.CDHC.y)) %>%
    select(-c(enrichedIn.CDHC.y))%>%
    left_join(missing_mgs.uchc.df[,c(6,8)], by = c('MGS'='bins'), suffix = c('', '.y')) %>%
    mutate(enrichedIn.UCHC = coalesce(enrichedIn.UCHC, enrichedIn.UCHC.y)) %>%
    select(-c(enrichedIn.UCHC.y))%>%
    left_join(missing_mgs.cduc.df[,c(6,8)], by = c('MGS'='bins'), suffix = c('', '.y')) %>%
    mutate(enrichedIn.CDUC = coalesce(enrichedIn.CDUC, enrichedIn.CDUC.y)) %>%
    select(-c(enrichedIn.CDUC.y))

DAmeans.all.mod_overlap_count_incCDUC<-DAmeans.all.mod_overlap%>%
  count(enrichedIn.CDUC,enrichedIn.IBDHC,enrichedIn.CDHC, enrichedIn.UCHC)
DAmeans.all.mod_overlap_count_incCDUC

DAmeans.all.mod_overlap_count1<-DAmeans.all.mod_overlap%>%
  count(enrichedIn.IBDHC,enrichedIn.CDHC, enrichedIn.UCHC)%>%
  mutate(group=paste0("IBD_",enrichedIn.IBDHC,"_CD_",enrichedIn.CDHC,"_UC_",enrichedIn.UCHC))%>%
  mutate(group2=c("IBD_CD_UC","IBD_CD","IBD_UC","IBD","IBD_CD_UC","IBD_CD","IBD_UC","IBD","CD_UC","CD","CD","UC","UC","non-sig"))%>%
  mutate(group3=ifelse(grepl("control",group),"control",ifelse(grepl("disease",group),"disease",NA)))
DAmeans.all.mod_overlap_count1$group2<-factor(DAmeans.all.mod_overlap_count1$group2, levels = c("IBD_CD_UC","IBD_CD","IBD_UC","CD_UC","IBD","CD","UC","non-sig"))

nSums<- DAmeans.all.mod_overlap_count1%>%
  filter(group2!="non-sig")%>%
  group_by(group2) %>%
  summarise(total=sum(n))

p_DAoverlap<-ggplot(DAmeans.all.mod_overlap_count1%>%filter(group2!="non-sig"), aes(x=group2,n))+
  geom_bar(stat = "identity", aes(fill=group3))+
  #geom_label(aes(label=n))+
  geom_text(data=nSums ,aes(x=group2,y=total,label=total,fill=NULL),
            nudge_y = 10)+
  scale_fill_manual(values=col_IBD2)+
  theme_bw()+
  theme(legend.position=c(.7,.7), legend.box="vertical", legend.margin=margin(),
        axis.text.x=element_blank(),
        axis.title.x=element_blank(),
        axis.ticks.x=element_blank())+
  guides(fill=guide_legend(title="Enriched in",keywidth=0.3,keyheight=0.1,default.unit="cm"))

DAmeans.all.mod_overlap_count2<-DAmeans.all.mod_overlap_count1%>%
  filter(group2!="non-sig")%>%
  distinct(group2)%>%
  mutate(head=c(NA,NA,NA,NA,NA,NA,NA))%>%
  mutate(IBD=c(1,1,1,1,NA,NA,NA))%>%
  mutate(CD=c(1,1,NA,NA,1,1,NA))%>%
  mutate(UC=c(1,NA,1,NA,1,NA,1))%>%
  mutate(xxx=c(NA,NA,NA,NA,NA,NA,NA))
DAmeans.all.mod_overlap_count2$group2<-factor(DAmeans.all.mod_overlap_count2$group2, levels = c("IBD_CD_UC","IBD_CD","IBD_UC","CD_UC","IBD","CD","UC"))
DAmeans.all.mod_overlap_count2<-DAmeans.all.mod_overlap_count2[order(DAmeans.all.mod_overlap_count2$group2),]

DAmeans.all.mod_overlap_count2<-DAmeans.all.mod_overlap_count2%>%
  column_to_rownames("group2")%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("group")

DAmeans.all.mod_overlap_count2<-DAmeans.all.mod_overlap_count2%>%gather(a,b,-group)
DAmeans.all.mod_overlap_count2$a<-factor(DAmeans.all.mod_overlap_count2$a, levels = c("IBD_CD_UC","IBD_CD","IBD_UC","CD_UC","IBD","CD","UC"))
DAmeans.all.mod_overlap_count2$group<-factor(DAmeans.all.mod_overlap_count2$group, levels = c("xxx","UC","CD","IBD","head"))


p_DAoverlap2<-ggplot(DAmeans.all.mod_overlap_count2, aes(a,group))+
  geom_point(aes(size=b))+
  theme_classic()+
  theme(legend.position="none",
        axis.text=element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title=element_blank(),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA))

plot_grid(p_DAoverlap,p_DAoverlap2,ncol=1, align = "v", axis="lr", rel_heights=c(1.5,1))
```

```{r fig.width=3, fig.height=3}
# remove IBD

DAmeans.all.mod_overlap_count_incCDUC_noIBD<-DAmeans.all.mod_overlap%>%
  count(enrichedIn.CDUC,enrichedIn.CDHC, enrichedIn.UCHC)
DAmeans.all.mod_overlap_count_incCDUC_noIBD

DAmeans.all.mod_overlap_noIBD_count1<-DAmeans.all.mod_overlap%>%
  count(enrichedIn.CDHC, enrichedIn.UCHC)%>%
  mutate(group=paste0("CD_",enrichedIn.CDHC,"_UC_",enrichedIn.UCHC))%>%
  mutate(group2=c("CD_UC","CD","CD_UC","CD","UC","UC","non-sig"))%>%
  mutate(group3=ifelse(grepl("control",group),"control",ifelse(grepl("disease",group),"disease",NA)))
DAmeans.all.mod_overlap_noIBD_count1$group2<-factor(DAmeans.all.mod_overlap_noIBD_count1$group2, levels = c("CD_UC","CD","UC","non-sig"))

DAmeans.all.mod_overlap_noIBD_count1_split<-DAmeans.all.mod_overlap%>%
  count(enrichedIn.CDHC, enrichedIn.UCHC, CDHC, UCHC)%>%
  mutate(group=paste0("CD_",enrichedIn.CDHC,"_",CDHC,"_UC_",enrichedIn.UCHC,"_",UCHC))%>%
  mutate(group2=c("CD_UC","CD_UC","CD_UC","CD_UC","CD","CD","CD_UC","CD_UC","CD_UC","CD_UC","CD","CD","UC","UC","UC","UC","non-sig"))%>%
  mutate(group3=ifelse(grepl("control",group),"control",ifelse(grepl("disease",group),"disease",NA)))%>%
  mutate(group4=paste0(CDHC,"_",UCHC))%>%
  mutate(group5=paste0(enrichedIn.CDHC,"_",CDHC,"_",enrichedIn.UCHC,"_",UCHC))%>%
  mutate(group5=gsub("_non-sig_non-sig","",group5))%>%
  mutate(group5=gsub("non-sig_non-sig_","",group5))%>%
  mutate(group5=gsub("control_robust_control_robust","control_robust",group5))%>%
  mutate(group5=gsub("control_variable_control_variable","control_variable",group5))%>%
  mutate(group5=gsub("disease_robust_disease_robust","disease_robust",group5))%>%
  mutate(group5=gsub("disease_variable_disease_variable","disease_variable",group5))%>%
  mutate(group5=gsub("control_robust_control_variable","control_variableUC",group5))%>%
  mutate(group5=gsub("disease_robust_disease_variable","disease_variableUC",group5))%>%
  mutate(group5=gsub("control_variable_control_robust","control_variableCD",group5))%>%
  mutate(group5=gsub("disease_variable_disease_robust","disease_variableCD",group5))%>%
  mutate(group5=ifelse(group2 != "CD_UC" & grepl("variable",group5), paste0(group5,group2), group5))
DAmeans.all.mod_overlap_noIBD_count1_split$group2<-factor(DAmeans.all.mod_overlap_noIBD_count1_split$group2, levels = c("CD_UC","CD","UC","non-sig"))
DAmeans.all.mod_overlap_noIBD_count1_split$group5<-factor(DAmeans.all.mod_overlap_noIBD_count1_split$group5, levels = c("control_robust","control_variableCD","control_variableUC","control_variable","disease_robust","disease_variableCD","disease_variableUC","disease_variable"))

nSums_noIBD<- DAmeans.all.mod_overlap_noIBD_count1%>%
  filter(group2!="non-sig")%>%
  group_by(group2) %>%
  summarise(total=sum(n))

nSums_noIBD_split<- DAmeans.all.mod_overlap_noIBD_count1_split%>%
  filter(group2!="non-sig")%>%
  group_by(group2) %>%
  summarise(total=sum(n))

# get proportions of overlap
nSums_noIBD_split%>%
  mutate(
    proportionUC=ifelse(grepl("UC",group2),
      total/sum((nSums_noIBD_split%>%filter(grepl("UC",group2)))[["total"]]),
      NA
      ),
    proportionCD=ifelse(grepl("CD",group2),
      total/sum((nSums_noIBD_split%>%filter(grepl("CD",group2)))[["total"]]),
      NA
      )
    )

# get proportions of overlap UC-CD and ctrl-disease direction
directionCDUC.df<-DAmeans.all.mod_overlap%>%
  count(enrichedIn.CDUC,enrichedIn.IBDHC)%>%
  filter(enrichedIn.CDUC!="non-sig")%>%
  mutate(IBDlike=ifelse(enrichedIn.CDUC=="CD" & enrichedIn.IBDHC=="disease", "same", 
                       ifelse(enrichedIn.CDUC=="UC" & enrichedIn.IBDHC=="control", "same",
                              ifelse(enrichedIn.CDUC=="CD" & enrichedIn.IBDHC=="control", "opposite",
                                ifelse(enrichedIn.CDUC=="CD" & enrichedIn.IBDHC=="control", "opposite",
                                "non-sig")))))

directionCDUC.df%>%
  group_by(IBDlike)%>%
  summarize(n=sum(n))%>%
  mutate(proportion=n/sum(directionCDUC.df$n))


p_DAoverlap_noIBD<-ggplot(DAmeans.all.mod_overlap_noIBD_count1%>%filter(group2!="non-sig"), aes(x=group2,n))+
  geom_bar(stat = "identity", aes(fill=group3))+
  #geom_label(aes(label=n))+
  geom_text(data=nSums_noIBD ,aes(x=group2,y=total,label=total,fill=NULL),
            nudge_y = 10)+
  scale_fill_manual(values=col_IBD2)+
  theme_bw()+
  theme(legend.position=c(.7,.7), legend.box="vertical", legend.margin=margin(),
        axis.text.x=element_blank(),
        axis.title.x=element_blank(),
        axis.ticks.x=element_blank())+ 
  guides(fill=guide_legend(title="Enriched in",keywidth=0.3,keyheight=0.1,default.unit="cm"))

p_DAoverlap_noIBD_split<-ggplot(DAmeans.all.mod_overlap_noIBD_count1_split%>%filter(group2!="non-sig"), aes(x=group2,n))+
  geom_bar(stat = "identity", aes(fill=group5))+
  #geom_label(aes(label=n))+
  geom_text(data=nSums_noIBD ,aes(x=group2,y=total,label=total,fill=NULL),
            nudge_y = 10)+
  scale_fill_manual(values=col_IBD3, breaks=c("control_robust","control_variableCD","control_variableUC","control_variable","disease_robust","disease_variableCD","disease_variableUC","disease_variable"))+
  theme_bw()+
  theme(legend.position=c(.7,.7), legend.box="vertical", legend.margin=margin(),
        axis.text.x=element_blank(),
        axis.title.x=element_blank(),
        axis.ticks.x=element_blank())+ 
  guides(fill=guide_legend(title="Enriched in",keywidth=0.3,keyheight=0.1,default.unit="cm"))



DAmeans.all.mod_overlap_noIBD_count2<-DAmeans.all.mod_overlap_noIBD_count1%>%
  filter(group2!="non-sig")%>%
  distinct(group2)%>%
  mutate(head=c(NA,NA,NA))%>%
  mutate(CD=c(1,1,NA))%>%
  mutate(UC=c(1,NA,1))%>%
  mutate(xxx=c(NA,NA,NA))
DAmeans.all.mod_overlap_noIBD_count2$group2<-factor(DAmeans.all.mod_overlap_noIBD_count2$group2, levels = c("CD_UC","CD","UC"))
DAmeans.all.mod_overlap_noIBD_count2<-DAmeans.all.mod_overlap_noIBD_count2[order(DAmeans.all.mod_overlap_noIBD_count2$group2),]

DAmeans.all.mod_overlap_noIBD_count2<-DAmeans.all.mod_overlap_noIBD_count2%>%
  column_to_rownames("group2")%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("group")

DAmeans.all.mod_overlap_noIBD_count2<-DAmeans.all.mod_overlap_noIBD_count2%>%gather(a,b,-group)
DAmeans.all.mod_overlap_noIBD_count2$a<-factor(DAmeans.all.mod_overlap_noIBD_count2$a, levels = c("CD_UC","CD","UC"))
DAmeans.all.mod_overlap_noIBD_count2$group<-factor(DAmeans.all.mod_overlap_noIBD_count2$group, levels = c("xxx","UC","CD","head"))


p_DAoverlap2_noIBD<-ggplot(DAmeans.all.mod_overlap_noIBD_count2, aes(a,group))+
  geom_point(aes(size=b))+
  theme_classic()+
  theme(legend.position="none",
        axis.text=element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title=element_blank(),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA))

plot_grid(p_DAoverlap_noIBD,p_DAoverlap2_noIBD,ncol=1, align = "v", axis="lr", rel_heights=c(1.5,1))

```


## plot mean results


```{r}
#exclude CD-UC for now
DAmeans.topMGS<-DAmeans.topMGS%>%
  mutate(significance=ifelse(robustDA=="robust","robust","non-significant/variable"))%>%
  mutate(enrichment=ifelse(meanTE>0,"Healthy","Disease"))%>%
  mutate(enrichment2=ifelse(meanTE>0,"Healthy",gsub("-HC","",comparison)))%>%
  mutate(enrichment2=ifelse(comparison=="CD-UC",ifelse(meanTE>0,"UC","CD"),enrichment2))%>%
  mutate(Taxonomy=gsub(';MGS.*','',MGS))%>%
  mutate(SpeciesMGS=paste0(gsub('.*;','',Taxonomy)," (",gsub('.*;MGS.','MGS.',MGS),")"))%>%
  mutate(MGS=gsub('.*;MGS.','MGS.',MGS))%>%
  separate(Taxonomy, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'), sep=';')

DAmeans.topMGS.tax<-DAmeans.topMGS%>%
  arrange(factor(SpeciesMGS, levels = meanTE))%>%
  mutate(SpeciesMGS2 = forcats::fct_inorder(SpeciesMGS))%>%
  mutate(meanTE2=ifelse(robustDA=="robust",meanTE,0))

DAmeans.topMGS.tax<-DAmeans.topMGS.tax%>%
  left_join(phyCol.df,by="Phylum")
# 
# DAmeans.topMGS.p1<-ggplot(DAmeans.topMGS.tax)+  geom_errorbar(aes(x=meanTE,y=reorder(SpeciesMGS2,meanTE),xmin=meanTE-stdevTE, xmax=meanTE+stdevTE), width=.1, color="grey70")+
#   geom_point(aes(x=meanTE,y=reorder(SpeciesMGS2,meanTE),color=enrichment2,shape=comparison,alpha=significance), size=3)+
#   scale_color_manual(values=col_IBD2)+
#   scale_shape_manual(values=c(15,16,17,18))+
#   geom_vline(xintercept=0, linetype="dashed", color="grey50")+
#   scale_alpha_discrete(range = c(0.2, 0.85))+
#   guides(color = guide_legend(override.aes = list(alpha = 1),keywidth=0.1,keyheight=0.1,default.unit="cm",title="enrichment"),
#          shape = guide_legend(keywidth=0.1,keyheight=0.1,default.unit="cm"),
#          alpha = guide_legend(keywidth=0.1,keyheight=0.1,default.unit="cm"))+
#   theme_bw() +
#   theme(legend.position=c(.2,.8), legend.box="vertical", legend.margin=margin())+
#   ylab("Species (MGS)")
# DAmeans.topMGS.p1
# xdf<-data.frame(SpeciesMGS2=layer_scales(DAmeans.topMGS.p1)$y$range$range)
# xxdf<-xdf%>%
#   left_join(DAmeans.topMGS.tax%>%select(c(SpeciesMGS2,PhylumColor)), by="SpeciesMGS2")%>%
#   distinct()
# DAmeans.topMGS.p2<-DAmeans.topMGS.p1+
#   theme(axis.text.y = element_text(colour=xxdf$PhylumColor))
# 
# DAmeans.topMGS.tax.cduc<-DAmeans.topMGS.tax%>%filter(comparison=="CD-UC")
# xdf<-data.frame(SpeciesMGS2=layer_scales(DAmeans.topMGS.p1)$y$range$range)
# DAmeans.topMGS.tax.cduc.sort<-xdf%>%
#   left_join(DAmeans.topMGS.tax.cduc, by="SpeciesMGS2")%>%
#   distinct()
# DAmeans.topMGS.tax.cduc.sort$nr<-seq.int(nrow(xdf))
# 
# DAmeans.topMGS.p3<-ggplot(DAmeans.topMGS.tax.cduc.sort)+
#   geom_tile(aes(x="x",y=reorder(SpeciesMGS2,nr),fill=meanTE2))+
#   scale_fill_gradientn(name="",colours=c("#E8A40033","#FFFFFF","#9370DB"),na.value = "transparent",
#                            breaks=c(-5,0,5),labels=c("UC","","CD"),
#                            limits=c(-5,5))+
#   theme_classic()+
#   theme(axis.text=element_blank(),
#         axis.title = element_blank(),
#         axis.line = element_blank(),
#         axis.ticks = element_blank(),
#         legend.position="bottom",
#         legend.direction="vertical",
#         legend.key.height= unit(0.2, 'cm'))

```

```{r}
# DAmeans.topMGS.p1b<-ggplot(DAmeans.topMGS.tax%>%filter(comparison!="IBD-HC"))+
#   geom_errorbar(aes(x=meanTE,y=reorder(SpeciesMGS2,meanTE),xmin=meanTE-stdevTE, xmax=meanTE+stdevTE), width=.1, color="grey70")+
#   geom_point(aes(x=meanTE,y=reorder(SpeciesMGS2,meanTE),color=enrichment2,shape=comparison,alpha=significance), size=3)+
#   scale_color_manual(values=col_IBD2)+
#   scale_shape_manual(values=c(15,16,17,18))+
#   geom_vline(xintercept=0, linetype="dashed", color="grey50")+
#   scale_alpha_discrete(range = c(0.2, 0.85))+
#   guides(color = guide_legend(override.aes = list(alpha = 1),keywidth=0.1,keyheight=0.1,default.unit="cm",title="enrichment"),
#          shape = guide_legend(keywidth=0.1,keyheight=0.1,default.unit="cm"),
#          alpha = guide_legend(keywidth=0.1,keyheight=0.1,default.unit="cm"))+
#   theme_bw() +
#   theme(legend.position=c(.2,.8), legend.box="vertical", legend.margin=margin())+
#   geom_label(aes(x=-2,y="Acetatifactor sp900066565 (MGS.39)", label="Healthy / UC"), fill="#40B0A633")+
#   geom_label(aes(x=2,y="Acetatifactor sp900066565 (MGS.39)", label="Disease"), fill="#E8A40033")+
#   ylab("Species (MGS)")
# DAmeans.topMGS.p1b
```

```{r}

#DAmeans

ord<-data.frame(MGS=spTree$tip.label)
test<- ord %>%
  left_join(MGStax, by="MGS") 

# identify Phylumn colors
colIBD<-sample(rainbow(length(unique(test$Phylum))))

gg_spTree<-ggtree(spTree, layout = 'circular') 
gg_spTree.ann<-gg_spTree %<+% test

newroot<-getMRCA(spTree,(gg_spTree.ann$data %>% filter(Kingdom=="Archaea"))$label) # identify Archaea root
#spTree.ArchRoot<-root(spTree,node=newroot) # reroot tree at Archaea
archaeaMGS<-(gg_spTree.ann$data %>% filter(Kingdom=="Archaea"))$label
spTree.ArchRoot<-root(spTree,outgroup=archaeaMGS, resolve.root=FALSE) # reroot tree with Archaea outgroup

DA_ext2<- DAmeans.all %>%
  #filter(robustDA=='robust')%>%
  mutate(enriched=ifelse(meanTE<0 & comparison=="IBD-HC","IBD",ifelse(meanTE<0 & comparison=="CD-HC","CD",ifelse(meanTE<0 & comparison=="UC-HC","UC",ifelse(meanTE<0 & comparison=="CD-UC","CD",ifelse(meanTE>0 & comparison!="CD-UC","healthy",ifelse(meanTE>0 & comparison=="CD-UC","UC",NA))))))) %>%
  mutate(enriched2 = ifelse(robustDA == 'robust', enriched, ifelse(robustDA == 'variable', 'variable','non-significant'))) %>%
  filter(enriched2!="non-significant")%>%
  mutate(MGStax=MGS)%>%
  mutate(MGS=gsub('.*;MGS.','MGS.',MGS))
  


gg_spTree.ArchRoot.ann<-ggtree(spTree.ArchRoot, 
                               layout = 'circular',
                               size=0) %<+% test 


robustTree1<-gg_spTree.ArchRoot.ann +
  geom_fruit(
         geom=geom_bar,
         data=DA_ext2%>%filter(comparison=="UC-HC"),
         stat = "identity",
         orientation="y", 
         mapping = aes(
                     y=MGS,
                     x=meanTE,
                     fill=enriched2),
         alpha=1,
         offset=0.06,
         pwidth=0.1,
         axis.params=list(axis = "y")) +
  scale_fill_manual(values=col_IBD2,na.value = NA)+
  new_scale_fill() +
  geom_fruit(
         geom=geom_bar,
         data=DA_ext2%>%filter(comparison=="CD-HC"),
         stat = "identity",
         orientation="y", 
         mapping = aes(
                     y=MGS,
                     x=meanTE,
                     fill=enriched2),
         alpha=1,
         offset=0.05,
         pwidth=0.1,
         #grid.params=list(alpha=0.2),
         axis.params=list(axis = "y")) +
  scale_fill_manual(values=col_IBD2,na.value = NA)+
  new_scale_fill() +
  geom_fruit(
         geom=geom_bar,
         data=DA_ext2%>%filter(comparison=="CD-UC"),
         stat = "identity",
         orientation="y", 
         mapping = aes(
                     y=MGS,
                     x=meanTE,
                     fill=enriched2),
         alpha=1,
         offset=0.05,
         pwidth=0.1,
         #grid.params=list(alpha=0.2),
         axis.params=list(axis = "y")) +
  scale_fill_manual(values=col_IBD2,na.value = NA)+
  new_scale_color() +
  geom_tree(aes(color=Phylum), size=0.25)+
  scale_color_manual(values=phy.col, limits = c("Firmicutes_A","Firmicutes_B","Firmicutes_C","Firmicutes_G","Firmicutes","Bacteroidota","Verrucomicrobiota","Proteobacteria","Desulfobacterota_I","Campylobacterota","Fusobacteriota","Cyanobacteria","Synergistota","Actinobacteriota","Thermoplasmatota","Methanobacteriota"))
robustTree1

treelegend<-ggpubr::get_legend(gg_spTree.ArchRoot.ann+
  geom_tree(aes(color=Phylum))+
  scale_color_manual(values=phy.col, limits = c("Firmicutes_A","Firmicutes_B","Firmicutes_C","Firmicutes_G","Firmicutes","Bacteroidota","Verrucomicrobiota","Proteobacteria","Desulfobacterota_I","Campylobacterota","Fusobacteriota","Cyanobacteria","Synergistota","Actinobacteriota","Thermoplasmatota","Methanobacteriota"))+theme(legend.position="top")+guides(color = guide_legend(nrow = 2)))

robustTree1.noL<-robustTree1+
  theme(legend.position="none")+
  geom_cladelabel(node=920, label="UC", 
                  color=col_IBD2["UC"], align=TRUE, offset=0, fontsize=3)+
  geom_cladelabel(node=920, label="control", 
                  color=col_IBD2["control"], align=TRUE, offset=0.3, fontsize=3)+
  geom_cladelabel(node=920, label="CD", 
                  color=col_IBD2["CD"], align=TRUE, offset=0.7, fontsize=3)+
  geom_cladelabel(node=920, label="control", 
                  color=col_IBD2["control"], align=TRUE, offset=1.05, fontsize=3)+
  geom_cladelabel(node=920, label="CD", 
                  color=col_IBD2["CD"], align=TRUE, offset=1.48, fontsize=3)+
  geom_cladelabel(node=920, label="UC", 
                  color=col_IBD2["UC"], align=TRUE, offset=1.83, fontsize=3)

robustTree1.noL

library(magick)
f <- tempfile(fileext="robustTree1.png")
ggsave(filename = f, plot = robustTree1.noL, width=7, height=7)
x <- image_read(f, density=1000)
y <- image_trim(x)

yy <- image_ggplot(y)
yy
```

```{r}

#nrow(DAmeans.all)

DAsumtab<-DAmeans.all%>%
  group_by(comparison)%>%
  count(robustDA)%>%
  spread(robustDA,n) %>%
  mutate(xx=sum(`non-sig`,`robust`,`variable`)) %>%
  mutate(`non-significant`=paste0(`non-sig`," (",round((`non-sig`/xx)*100),"%)"))%>%
  mutate(variable=paste0(variable," (",round((variable/xx)*100),"%)"))%>%
  mutate(robust=paste0(robust," (",round((robust/xx)*100),"%)"))%>%
  select(-c(xx,`non-sig`))%>%
  mutate(comparison=gsub("HC","control",comparison))%>%
  rename("ns"="non-significant")

DAsumtab$comparison<-factor(DAsumtab$comparison,levels=c("IBD-control","CD-control","UC-control","CD-UC"))
DAsumtab


DAsumtab<-DAsumtab[order(DAsumtab$comparison), ]%>%
  filter(comparison!="IBD-control")

DAsumtab.obj<-formattable(DAsumtab[order(DAsumtab$comparison), ],
            list(`#` = formatter("span", style = ~ style(font.weight = "bold"))))
DAsumtab.obj

DAsumtab.obj.tab<-tableGrob(DAsumtab.obj,rows=c("","",""))
#DAsumtab.obj.tab
```



### make the plots using top MGS but efect size of first sample only

```{r}
#head(DAmeans.topMGS)
length(topMGSall)
#MGS=gsub(".*;MGS.","MGS.",bins)

metaDA.samp1.topMGS<-metaDA[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%topMGSall)%>%
  left_join(DAmeans,by = "MGS")%>%
  mutate(TE.random=-as.numeric(TE.random))%>%
  mutate(lower.random=-as.numeric(lower.random))%>%
  mutate(upper.random=-as.numeric(upper.random))
metaDA.cdhc.samp1.topMGS<-metaDA.cdhc[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%topMGSall)%>%
  left_join(DAmeans.cdhc,by = "MGS")    
metaDA.uchc.samp1.topMGS<-metaDA.uchc[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%topMGSall)%>%
  left_join(DAmeans.uchc,by = "MGS") 
metaDA.cduc.samp1.topMGS<-metaDA.cduc[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%topMGSall)%>%
  left_join(DAmeans.cduc,by = "MGS") 

DAsamp1.topMGS<-rbind(metaDA.samp1.topMGS,metaDA.cdhc.samp1.topMGS,metaDA.uchc.samp1.topMGS,metaDA.cduc.samp1.topMGS)

DAsamp1.topMGS.tax<-DAsamp1.topMGS %>%
  mutate(significance=ifelse(robustDA=="non-sig","znon-significant",robustDA))%>%
  mutate(enrichment=ifelse(meanTE>0,"Healthy","Disease"))%>%
  mutate(enrichment2=ifelse(meanTE>0,"Healthy",gsub("-HC","",comparison)))%>%
  mutate(enrichment2=ifelse(comparison=="CD-UC",ifelse(meanTE>0,"UC","CD"),enrichment2))%>%
  mutate(Taxonomy=gsub(';MGS.*','',MGS))%>%
  mutate(SpeciesMGS=paste0(gsub('.*;','',Taxonomy)," (",gsub('.*;MGS.','MGS.',MGS),")"))%>%
  mutate(MGS=gsub('.*;MGS.','MGS.',MGS))%>%
  separate(Taxonomy, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'), sep=';')


DAsamp1.topMGS.tax<-DAsamp1.topMGS.tax%>%
  mutate(TE.random=as.numeric(TE.random))%>%
  mutate(seTE.random=as.numeric(seTE.random))%>%
  mutate(TE.random=ifelse(p.adjust>q,NA,TE.random))%>%
  mutate(seTE.random=ifelse(p.adjust>q,NA,seTE.random))


DAsamp1.topMGS.tax<-DAsamp1.topMGS.tax%>%
  arrange(factor(SpeciesMGS, levels = TE.random))%>%
  mutate(SpeciesMGS2 = forcats::fct_inorder(SpeciesMGS))%>%
  mutate(meanTE2=ifelse(robustDA=="robust",meanTE,0))

DAsamp1.topMGS.tax<-DAsamp1.topMGS.tax%>%
  left_join(phyCol.df,by="Phylum")%>%
  mutate(comparison=gsub("HC","control",comparison))%>%
  filter(comparison!="IBD-control")

DAsamp1.topMGS.p1<-ggplot(DAsamp1.topMGS.tax)+#%>%
  geom_errorbar(aes(x=TE.random,y=reorder(SpeciesMGS2,meanTE),xmin=TE.random-seTE.random, xmax=TE.random+seTE.random), width=.3, color="grey70") +
  geom_errorbar(aes(x=meanTE,y=reorder(SpeciesMGS2,meanTE),xmin=meanTE-stdevTE, xmax=meanTE+stdevTE,color=comparison,alpha=significance), width=0, size=3.5)+ #color=enrichment2
  geom_point(aes(x=TE.random,y=reorder(SpeciesMGS2,meanTE),shape=comparison),color="black", size=1.3)+
  scale_color_manual(values=c("CD-control"=col_IBD2[["CD"]],"UC-control"=col_IBD2[["UC"]],"CD-UC"="orchid"), breaks=c("CD-control","UC-control","CD-UC"))+
  scale_shape_manual(values=c(0,1,2,5),breaks=c("CD-control","UC-control","CD-UC"))+#(values=c(15,16,17,18))+
  geom_vline(xintercept=0, linetype="dashed", color="grey50")+
  scale_alpha_discrete(range = c(1,0),breaks=c("robust", "variable"))+
  guides(color = guide_legend(override.aes = list(alpha = 1),keywidth=0.3,keyheight=0.1,default.unit="cm",title="resampling effect sizes"),
         shape = guide_legend(keywidth=0.3,keyheight=0.1,default.unit="cm",title="effect size"),
         alpha = guide_legend(keywidth=0.3,keyheight=0.1,default.unit="cm"))+
  scale_y_discrete(position = "right")+
  scale_x_reverse()+
  theme_bw() +
  theme(legend.position=c(.72,.8), legend.box="vertical", legend.margin=margin(),
        axis.text.y=element_text(size=10))+
  ylab("Top Species (MGS)")+
  xlab("Effect size")
DAsamp1.topMGS.p1

xdf<-data.frame(SpeciesMGS2=layer_scales(DAsamp1.topMGS.p1)$y$range$range)
xxdf<-xdf%>%
  left_join(DAsamp1.topMGS.tax%>%select(c(SpeciesMGS2,PhylumColor)), by="SpeciesMGS2")%>%
  distinct()
DAmeans.topMGS.p2<-DAsamp1.topMGS.p1+
  theme(axis.text.y = element_text(colour=xxdf$PhylumColor))
```

### make supplementary plot of ALL MGS but effect size of first sample only

```{r fig.height=21, fig.width=8}
cducMGS<-(DAmeans.cduc%>%filter(robustDA!="non-sig"))$MGS
cdhcMGS<-(DAmeans.cdhc%>%filter(robustDA!="non-sig"))$MGS
uchcMGS<-(DAmeans.uchc%>%filter(robustDA!="non-sig"))$MGS
#ibdMGS<-(DAmeans%>%filter(robustDA!="non-sig"))$MGS
allMGSall<-unique(c(cducMGS,cdhcMGS,uchcMGS))

metaDA.samp1.allMGS<-metaDA[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%allMGSall)%>%
  left_join(DAmeans,by = "MGS")%>%
  mutate(TE.random=-as.numeric(TE.random))%>%
  mutate(lower.random=-as.numeric(lower.random))%>%
  mutate(upper.random=-as.numeric(upper.random))
metaDA.cdhc.samp1.allMGS<-metaDA.cdhc[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%allMGSall)%>%
  left_join(DAmeans.cdhc,by = "MGS")    
metaDA.uchc.samp1.allMGS<-metaDA.uchc[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%allMGSall)%>%
  left_join(DAmeans.uchc,by = "MGS") 
metaDA.cduc.samp1.allMGS<-metaDA.cduc[[1]]%>%
  mutate(MGS=bins)%>%
  filter(MGS%in%allMGSall)%>%
  left_join(DAmeans.cduc,by = "MGS") 

DAsamp1.allMGS<-rbind(metaDA.samp1.allMGS,metaDA.cdhc.samp1.allMGS,metaDA.uchc.samp1.allMGS,metaDA.cduc.samp1.allMGS)

DAsamp1.allMGS.tax<-DAsamp1.allMGS %>%
  mutate(significance=ifelse(robustDA=="non-sig","znon-significant",robustDA))%>%
  mutate(enrichment=ifelse(meanTE>0,"Healthy","Disease"))%>%
  mutate(enrichment2=ifelse(meanTE>0,"Healthy",gsub("-HC","",comparison)))%>%
  mutate(enrichment2=ifelse(comparison=="CD-UC",ifelse(meanTE>0,"UC","CD"),enrichment2))%>%
  mutate(Taxonomy=gsub(';MGS.*','',MGS))%>%
  mutate(SpeciesMGS=paste0(gsub('.*;','',Taxonomy)," (",gsub('.*;MGS.','MGS.',MGS),")"))%>%
  mutate(MGS=gsub('.*;MGS.','MGS.',MGS))%>%
  separate(Taxonomy, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'), sep=';')


DAsamp1.allMGS.tax<-DAsamp1.allMGS.tax%>%
  mutate(TE.random=as.numeric(TE.random))%>%
  mutate(seTE.random=as.numeric(seTE.random))%>%
  mutate(TE.random=ifelse(p.adjust>q,NA,TE.random))%>%
  mutate(seTE.random=ifelse(p.adjust>q,NA,seTE.random))

uniqTE<-unique(DAsamp1.allMGS.tax$TE.random)
DAsamp1.allMGS.tax<-DAsamp1.allMGS.tax%>%
  arrange(factor(SpeciesMGS, levels = uniqTE))%>%
  mutate(SpeciesMGS2 = forcats::fct_inorder(SpeciesMGS))%>%
  mutate(meanTE2=ifelse(robustDA=="robust",meanTE,0))

DAsamp1.allMGS.tax<-DAsamp1.allMGS.tax%>%
  left_join(phyCol.df,by="Phylum")%>%
  mutate(comparison=gsub("HC","control",comparison))%>%
  filter(comparison!="IBD-control")

DAsamp1.allMGS.p1<-ggplot(DAsamp1.allMGS.tax)+#%>%
  geom_errorbar(aes(x=TE.random,y=reorder(SpeciesMGS2,meanTE),xmin=TE.random-seTE.random, xmax=TE.random+seTE.random), width=.3, color="grey70") +
  geom_errorbar(aes(x=meanTE,y=reorder(SpeciesMGS2,meanTE),xmin=meanTE-stdevTE, xmax=meanTE+stdevTE,color=comparison,alpha=significance), width=0, size=3.5)+ #color=enrichment2
  geom_point(aes(x=TE.random,y=reorder(SpeciesMGS2,meanTE),shape=comparison),color="black", size=1.3)+
  scale_color_manual(values=c("CD-control"=col_IBD2[["CD"]],"UC-control"=col_IBD2[["UC"]],"CD-UC"="orchid"), breaks=c("CD-control","UC-control","CD-UC"))+
  scale_shape_manual(values=c(0,1,2,5),breaks=c("CD-control","UC-control","CD-UC"))+#(values=c(15,16,17,18))+
  geom_vline(xintercept=0, linetype="dashed", color="grey50")+
  scale_alpha_discrete(range = c(1,0),breaks=c("robust", "variable"))+
  guides(color = guide_legend(override.aes = list(alpha = 1),keywidth=0.3,keyheight=0.1,default.unit="cm",title="resampling effect sizes"),
         shape = guide_legend(keywidth=0.3,keyheight=0.1,default.unit="cm",title="effect size"),
         alpha = guide_legend(keywidth=0.3,keyheight=0.1,default.unit="cm"))+
  scale_y_discrete(position = "right")+
  scale_x_reverse()+
  theme_bw() +
  theme(legend.position=c(.75,.9), legend.box="vertical", legend.margin=margin(),
        axis.text.y=element_text(size=10))+
  ylab("all Species (MGS)")+
  xlab("Effect size")
DAsamp1.allMGS.p1

xdfall<-data.frame(SpeciesMGS2=layer_scales(DAsamp1.allMGS.p1)$y$range$range)
xxdfall<-xdfall%>%
  left_join(DAsamp1.allMGS.tax%>%select(c(SpeciesMGS2,PhylumColor)), by="SpeciesMGS2")%>%
  distinct()
DAmeans.allMGS.p2<-DAsamp1.allMGS.p1+
  theme(axis.text.y = element_text(colour=xxdfall$PhylumColor))
DAmeans.allMGS.p2

pdf(paste0(PATH,"suppl.DAq0.1.allMGS.pdf"), width=8, height=23)
DAmeans.allMGS.p2
dev.off()
ggsave(paste0(PATH,"suppl.DAq0.1.allMGS.png"), DAmeans.allMGS.p2,width=8, height=23)
```

```{r}
# check % of depletion phyla
phylaCountsDA<-DAsamp1.allMGS.tax%>%
  group_by(comparison)%>%
  count(Phylum)

# CD - control
DAsamp1.allMGS.tax.CDHC<-DAsamp1.allMGS.tax%>%
  filter(comparison=="CD-control")%>%
  filter(meanTE2>0)%>%
  filter(p.adjust<q)%>%
  count(Phylum)
sumDA_CDHC<-(DAsamp1.allMGS.tax.CDHC%>%summarize(sum(n)))[[1,1]]
DAsamp1.allMGS.tax.CDHC%>%
  mutate(prop=n/sumDA_CDHC)

# UC-control
DAsamp1.allMGS.tax.UCHC<-DAsamp1.allMGS.tax%>%
  filter(comparison=="UC-control")%>%
  filter(meanTE2>0)%>%
  filter(p.adjust<q)%>%
  count(Phylum)
  
sumDA_UCHC<-(DAsamp1.allMGS.tax.UCHC%>%summarize(sum(n)))[[1,1]]
DAsamp1.allMGS.tax.UCHC%>%
  mutate(prop=n/sumDA_UCHC)
```

```{r fig.width=6, fig.height=6}
direction<-ggplot()+
  geom_text(aes(x=1,y=1,label="control"),hjust="inward")+
  geom_text(aes(x=2,y=1,label="disease"),hjust="inward")+ 
  geom_text(aes(x=1,y=1.5,label="UC"),hjust="inward")+
  geom_text(aes(x=2,y=1.5,label="CD"),hjust="inward")+ 
  geom_text(aes(x=1.5,y=1.25,label="enriched in"),size=4)+
  geom_segment(aes(x = 1.35, y = 1, xend = 1.20, yend = 1),
                  arrow = arrow(length = unit(0.3, "cm")))+ 
  geom_segment(aes(x = 1.65, y = 1, xend = 1.80, yend = 1),
                  arrow = arrow(length = unit(0.3, "cm")))+
  geom_segment(aes(x = 1.35, y = 1.5, xend = 1.1, yend = 1.5),
                  arrow = arrow(length = unit(0.3, "cm")))+ 
  geom_segment(aes(x = 1.65, y = 1.5, xend = 1.9, yend = 1.5),
                  arrow = arrow(length = unit(0.3, "cm")))+  
  ylim(0,2) +
  theme_nothing()

DAmeans.topMGS.p3<-plot_grid(direction+theme(plot.margin=margin(b=-0.3,unit="cm")),DAmeans.topMGS.p2+
        theme(plot.margin=margin(t=-0.3,unit="cm")),ncol=1,rel_heights = c(1,10), align = "v")
DAmeans.topMGS.p3

```

```{r}
# correlation with inflammation index


df_cor_all_DAibd_rhoVSmeanTE<-df_cor_all_DAibd_all_sigs%>%
  filter(!is.na(effect))%>%
  select(c(MGS,cohort,measure,effect,sample))%>%
  spread(measure,effect)%>%
  gather(comparison,meanTE,c("meanTE.CDUC","meanTE.IBDHC","meanTE.UCHC","meanTE.CDHC"))%>%
  mutate(comparison=gsub("meanTE.","",comparison))%>%
  mutate(comparison=gsub("HC"," vs. control",comparison))%>%
  mutate(comparison=gsub("CDUC","CD vs. UC",comparison))%>%
  separate(MGS, into = c('Kingdom', 'Phylum', 'Class', 'Order', 'Family','Genus', 'Species','MGS'), sep=";")%>%
  mutate(MGS=paste0(Species," (",MGS,")"))

df_cor_all_DAibd_meanRhoVSmeanTE<-df_cor_all_DAibd_rhoVSmeanTE%>%
  mutate(rho=as.numeric(rho))%>%
  group_by(MGS)%>%
  summarize(meanRho=mean(rho))%>%
  left_join(df_cor_all_DAibd_rhoVSmeanTE, by="MGS")%>%
  distinct(MGS, comparison,.keep_all = TRUE)

# IBD only
df_cor_all_DAibd_rhoVSmeanTE_IBD<-df_cor_all_DAibd_all_sigs_IBD%>%
  filter(!is.na(effect))%>%
  select(c(MGS,cohort,measure,effect,sample))%>%
  spread(measure,effect)%>%
  gather(comparison,meanTE,c("meanTE.CDUC","meanTE.IBDHC","meanTE.UCHC","meanTE.CDHC"))%>%
  mutate(comparison=gsub("meanTE.","",comparison))%>%
  mutate(comparison=gsub("HC"," vs. control",comparison))%>%
  mutate(comparison=gsub("CDUC","CD vs. UC",comparison))%>%
  separate(MGS, into = c('Kingdom', 'Phylum', 'Class', 'Order', 'Family','Genus', 'Species','MGS'), sep=";")%>%
  mutate(MGS=paste0(Species," (",MGS,")"))

df_cor_all_DAibd_meanRhoVSmeanTE_IBD<-df_cor_all_DAibd_rhoVSmeanTE_IBD%>%
  mutate(rho=as.numeric(rho))%>%
  group_by(MGS)%>%
  summarize(meanRho=mean(rho))%>%
  left_join(df_cor_all_DAibd_rhoVSmeanTE, by="MGS")%>%
  distinct(MGS, comparison,.keep_all = TRUE)

# CTRL only
df_cor_all_DAibd_rhoVSmeanTE_CTRL<-df_cor_all_DAibd_all_sigs_CTRL%>%
  filter(!is.na(effect))%>%
  select(c(MGS,cohort,measure,effect,sample))%>%
  spread(measure,effect)%>%
  gather(comparison,meanTE,c("meanTE.CDUC","meanTE.IBDHC","meanTE.UCHC","meanTE.CDHC"))%>%
  mutate(comparison=gsub("meanTE.","",comparison))%>%
  mutate(comparison=gsub("HC"," vs. control",comparison))%>%
  mutate(comparison=gsub("CDUC","CD vs. UC",comparison))%>%
  separate(MGS, into = c('Kingdom', 'Phylum', 'Class', 'Order', 'Family','Genus', 'Species','MGS'), sep=";")%>%
  mutate(MGS=paste0(Species," (",MGS,")"))

df_cor_all_DAibd_meanRhoVSmeanTE_CTRL<-df_cor_all_DAibd_rhoVSmeanTE_CTRL%>%
  mutate(rho=as.numeric(rho))%>%
  group_by(MGS)%>%
  summarize(meanRho=mean(rho))%>%
  left_join(df_cor_all_DAibd_rhoVSmeanTE, by="MGS")%>%
  distinct(MGS, comparison,.keep_all = TRUE)

(df_cor_all_DAibd_meanRhoVSmeanTE%>%filter(!is.na(meanTE)))$MGS%>%unique()%>%length()

# p2_cor_all_DAibd_all_sigs<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE%>%
#                                     mutate(rho=as.numeric(rho))%>%
#                                     filter(comparison!="IBD vs. control"),
#                                   aes(rho,meanTE))+
#     geom_hline(yintercept = 0, linetype=2, color="grey80") +
#     geom_vline(xintercept = 0, linetype=2, color="grey80") +
#     #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
#     #geom_point(size=1, alpha=0.7, aes(color=cohort)) +
#     geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
#     facet_wrap(.~comparison, scales = "free_x") +
#     ylab("Mean differential abundance effect size (mean TE)") +
#     scale_x_reverse()+
#     theme_bw()+
#     theme(panel.grid = element_blank())
# p2_cor_all_DAibd_all_sigs
# 
# 
df_cor_all_DAibd_rhoVSmeanTE_1tp<-df_cor_all_DAibd_meanRhoVSmeanTE%>%
                                    mutate(rho=as.numeric(rho))%>%
                                    filter(comparison!="IBD vs. control")%>%
                                    distinct(MGS,cohort,comparison,.keep_all = TRUE)
df_cor_all_DAibd_rhoVSmeanTE_1tp$comparison<-factor(df_cor_all_DAibd_rhoVSmeanTE_1tp$comparison, levels=c("CD vs. control","UC vs. control","CD vs. UC"))
# p3_cor_all_DAibd_all_sigs<-ggplot(df_cor_all_DAibd_rhoVSmeanTE_1tp,
# #                                  mutate(rho=as.numeric(rho))%>%
#                                   aes(rho,meanTE))+
#     geom_hline(yintercept = 0, linetype=2, color="grey80") +
#     geom_vline(xintercept = 0, linetype=2, color="grey80") +
#     #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
#     #geom_point(size=1, alpha=0.7, aes(color=cohort)) +
#     geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
#     facet_wrap(.~comparison, scales = "free_x") +
#     ylab("Mean differential abundance\neffect size (mean TE)") +
#     xlab("Correlation of species abundance to inflammation index in each cohort (rho)") +
#     scale_x_reverse()+
#     scale_color_manual(values=phy.col)+
#     theme_bw()+
#     theme(panel.grid = element_blank())
# p3_cor_all_DAibd_all_sigs
```


```{r}
# get proportions
CDHC_DAandCorr<-df_cor_all_DAibd_rhoVSmeanTE_1tp%>%
  filter(comparison=="CD vs. control")%>%
  filter(!is.na(meanTE))%>%
  count(MGS)%>%
  nrow()

CDHC_sigN<-DAmeans.all%>%
  ungroup() %>%
  filter(comparison=="CD-HC")%>%
  filter(robustDA!="non-sig")%>%
  count()

CDHC_DAandCorr/CDHC_sigN

UCHC_DAandCorr<-df_cor_all_DAibd_rhoVSmeanTE_1tp%>%
  filter(comparison=="UC vs. control")%>%
  filter(!is.na(meanTE))%>%
  count(MGS)%>%
  nrow()

UCHC_sigN<-DAmeans.all%>%
  ungroup() %>%
  filter(comparison=="UC-HC")%>%
  filter(robustDA!="non-sig")%>%
  count()

UCHC_DAandCorr/UCHC_sigN

# IBD
IBDHC_DAandCorr<-df_cor_all_DAibd_meanRhoVSmeanTE%>%
  filter(comparison=="IBD vs. control")%>%
  filter(!is.na(meanTE))%>%
  count(MGS)%>%
  nrow()

IBDHC_sigN<-DAmeans.all%>%
  ungroup() %>%
  filter(comparison=="IBD-HC")%>%
  filter(robustDA!="non-sig")%>%
  count()

IBDHC_DAandCorr/IBDHC_sigN

```


```{r}
## correlations DA infl idx
# all
direct.value<-df_cor_all_DAibd_meanRhoVSmeanTE%>%
  mutate(rho=as.numeric(rho))%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="IBD vs. control")
lm.ibdctrl<-lm(meanTE ~ meanRho, data=direct.value)
summary(lm.ibdctrl)
cor.ibdctrl<-cor.test(direct.value$meanTE, direct.value$meanRho, use = "complete.obs", method="spearman")

direct.value.cdctrl<-df_cor_all_DAibd_meanRhoVSmeanTE%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="CD vs. control")
lm.cdctrl<-lm(meanTE ~ meanRho, data=direct.value.cdctrl)
summary(lm.cdctrl)
cor.cdctrl<-cor.test(direct.value.cdctrl$meanTE, direct.value.cdctrl$meanRho, use = "complete.obs", method="spearman")

direct.value.ucctrl<-df_cor_all_DAibd_meanRhoVSmeanTE%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="UC vs. control")
lm.ucctrl<-lm(meanTE ~ meanRho, data=direct.value.ucctrl)
summary(lm.ucctrl)
cor.ucctrl<-cor.test(direct.value.ucctrl$meanTE, direct.value.ucctrl$meanRho, use = "complete.obs", method="spearman")

#IBD only
direct.value.ibdctrl_IBD<-df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="IBD vs. control")
lm.ibdctrl_IBD<-lm(meanTE ~ meanRho, data=direct.value.ibdctrl_IBD)
summary(lm.ibdctrl_IBD)
cor.ibdctrl_IBD<-cor.test(direct.value.ibdctrl_IBD$meanTE, direct.value.ibdctrl_IBD$meanRho, use = "complete.obs", method="spearman")

direct.value.cdctrl_IBD<-df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="CD vs. control")
lm.cdctrl_IBD<-lm(meanTE ~ meanRho, data=direct.value.cdctrl_IBD)
summary(lm.cdctrl_IBD)
cor.cdctrl_IBD<-cor.test(direct.value.cdctrl_IBD$meanTE, direct.value.cdctrl_IBD$meanRho, use = "complete.obs", method="spearman")

direct.value.ucctrl_IBD<-df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="UC vs. control")
lm.ucctrl_IBD<-lm(meanTE ~ meanRho, data=direct.value.ucctrl_IBD)
summary(lm.ucctrl_IBD)
cor.ucctrl_IBD<-cor.test(direct.value.ucctrl_IBD$meanTE, direct.value.ucctrl_IBD$meanRho, use = "complete.obs", method="spearman")

#controls only
direct.value.ibdctrl_CTRL<-df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="IBD vs. control")
lm.ibdctrl_CTRL<-lm(meanTE ~ meanRho, data=direct.value.ibdctrl_CTRL)
summary(lm.ibdctrl_CTRL)
cor.ibdctrl_CTRL<-cor.test(direct.value.ibdctrl_CTRL$meanTE, direct.value.ibdctrl_CTRL$meanRho, use = "complete.obs", method="spearman")


direct.value.cdctrl_CTRL<-df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="CD vs. control")
lm.cdctrl_CTRL<-lm(meanTE ~ meanRho, data=direct.value.cdctrl_CTRL)
summary(lm.cdctrl_CTRL)
cor.cdctrl_CTRL<-cor.test(direct.value.cdctrl_CTRL$meanTE, direct.value.cdctrl_CTRL$meanRho, use = "complete.obs", method="spearman")


direct.value.ucctrl_CTRL<-df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="UC vs. control")
lm.ucctrl_CTRL<-lm(meanTE ~ meanRho, data=direct.value.ucctrl_CTRL)
summary(lm.ucctrl_CTRL)
cor.ucctrl_CTRL<-cor.test(direct.value.ucctrl_CTRL$meanTE, direct.value.ucctrl_CTRL$meanRho, use = "complete.obs", method="spearman")


#individuals only
direct.value.ibdctrl_Ind<-MGScor_blInd_DA_gat%>%
  mutate(Direction=as.numeric(Direction))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="IBD vs. control")
lm.ibdctrl_Ind<-lm(meanTE ~ Direction, data=direct.value.ibdctrl_Ind)
summary(lm.ibdctrl_Ind)
cor.ibdctrl_Ind<-cor.test(direct.value.ibdctrl_Ind$meanTE, direct.value.ibdctrl_Ind$Direction, use = "complete.obs", method="spearman")


direct.value.cdctrl_Ind<-MGScor_blInd_DA_gat%>%
  mutate(Direction=as.numeric(Direction))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="CD vs. control")
lm.cdctrl_Ind<-lm(meanTE ~ Direction, data=direct.value.cdctrl_Ind)
summary(lm.cdctrl_Ind)
cor.cdctrl_Ind<-cor.test(direct.value.cdctrl_Ind$meanTE, direct.value.cdctrl_Ind$Direction, use = "complete.obs", method="spearman")


direct.value.ucctrl_Ind<-MGScor_blInd_DA_gat%>%
  mutate(Direction=as.numeric(Direction))%>%
  mutate(meanTE=as.numeric(meanTE))%>%
  filter(!is.na(meanTE))%>%
  filter(comparison=="UC vs. control")
lm.ucctrl_Ind<-lm(meanTE ~ Direction, data=direct.value.ucctrl_Ind)
summary(lm.ucctrl_Ind)
cor.ucctrl_Ind<-cor.test(direct.value.ucctrl_Ind$meanTE, direct.value.ucctrl_Ind$Direction, use = "complete.obs", method="spearman")

```


```{r}
rho='\u03c1'
# IBD vs controls
df_cor_all_DAibd_meanRhoVSmeanTE<-df_cor_all_DAibd_meanRhoVSmeanTE%>%
  mutate(rho=as.numeric(rho))%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))
backgrounds1 <- data.frame(
  xmin = c(-0.6, 0,-0.6, 0),
  xmax = c(0, 0.4,0, 0.4),
  ymin = c(-5,-5,0,0),
  ymax = c(0,0,6,6)
)
p1_cor_all_DA_IBD<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE%>%filter(comparison=="IBD vs. control"),aes(meanRho,meanTE))+
  # Add limited background rectangles
  geom_rect(data = backgrounds1,
            aes(xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax),
                fill = c("lightblue", "orange", "yellow", "grey50"),
            alpha = 0.1, inherit.aes = FALSE) +
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect\nsize IBD-controls") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle(paste0("All individuals\n",rho,"=",round(cor.ibdctrl$estimate,2),", p<2.2e-16"))
p1_cor_all_DA_IBD

df_cor_all_DAibd_meanRhoVSmeanTE_IBD<-df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%
  mutate(rho=as.numeric(rho))%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))
backgrounds2 <- data.frame(
  xmin = c(-0.7, 0,-0.7, 0),
  xmax = c(0, 0.4,0, 0.4),
  ymin = c(-5,-5,0,0),
  ymax = c(0,0,6,6)
)
p2_cor_ibd_DA_IBD<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%filter(comparison=="IBD vs. control"),aes(meanRho,meanTE))+
  # Add limited background rectangles
  geom_rect(data = backgrounds2,
            aes(xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax),
                fill = c("lightblue", "orange", "yellow", "grey50"),
            alpha = 0.1, inherit.aes = FALSE) +
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle(paste0("IBD individuals\n",rho,"=",round(cor.ibdctrl_IBD$estimate,2),", p=",signif(cor.ibdctrl_IBD$p.value,1)))
p2_cor_ibd_DA_IBD

df_cor_all_DAibd_meanRhoVSmeanTE_CTRL<-df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%
  mutate(rho=as.numeric(rho))%>%
  mutate(meanRho=as.numeric(meanRho))%>%
  mutate(meanTE=as.numeric(meanTE))
backgrounds3 <- data.frame(
  xmin = c(-0.9, 0,-0.9, 0),
  xmax = c(0, 0.7,0, 0.7),
  ymin = c(-5,-5,0,0),
  ymax = c(0,0,6,6)
)
p3_cor_ibd_DA_IBD<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%filter(comparison=="IBD vs. control"),aes(meanRho,meanTE))+
  # Add limited background rectangles
  geom_rect(data = backgrounds3,
            aes(xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax),
                fill = c("lightblue", "orange", "yellow", "grey50"),
            alpha = 0.1, inherit.aes = FALSE) +
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle(paste0("Control individuals\n",rho,"=",round(cor.ibdctrl_CTRL$estimate,2),", p=",signif(cor.ibdctrl_CTRL$p.value,1)))
p3_cor_ibd_DA_IBD

backgrounds4 <- data.frame(
  xmin = c(-0.03, 0,-0.03, 0),
  xmax = c(0, 0.02,0, 0.02),
  ymin = c(-5,-5,0,0),
  ymax = c(0,0,6,6)
)
p4_cor_blInd_DA_IBD<-ggplot(MGScor_blInd_DA_gat%>%filter(comparison=="IBD vs. control"),aes(Direction,meanTE))+
  # Add limited background rectangles
  geom_rect(data = backgrounds4,
            aes(xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax),
                fill = c("lightblue", "orange", "yellow", "grey50"),
            alpha = 0.1, inherit.aes = FALSE) +
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle(paste0("Longitudinal\n",rho,"=",round(cor.ibdctrl_Ind$estimate,2),", p=",signif(cor.ibdctrl_Ind$p.value,1)))
p4_cor_blInd_DA_IBD
```


```{r}

p4_cor_all_DAibd_all_sigs_IBD<-plot_grid(p1_cor_all_DA_IBD+ylab("IBD-association\n(effect size)")+theme(legend.position = "none", axis.title.y = element_text(size=11), axis.title.x = element_blank(), title = element_text(size=8)),
                                     p2_cor_ibd_DA_IBD+theme(legend.position = "none",  axis.title.x = element_blank(), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p3_cor_ibd_DA_IBD+
                                       xlab("Inflammation-association (Rho)")+
                                       theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p4_cor_blInd_DA_IBD+theme(legend.position = "none",  axis.title.x = element_blank(), axis.title.y = element_blank(), title = element_text(size=8)),
                                     nrow=1, rel_widths = c(1.2,1,1,1), align = "h")
p4_cor_all_DAibd_all_sigs_IBD


```



```{r}
# CD vs controls
p1_cor_all_DA_CD<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE%>%filter(comparison=="CD vs. control"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect\nsize (mean TE) CD-controls") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("All individuals")
p1_cor_all_DA_CD

p2_cor_ibd_DA_CD<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%filter(comparison=="CD vs. control"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("IBD individuals")
p2_cor_ibd_DA_CD

p3_cor_ibd_DA_CD<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%filter(comparison=="CD vs. control"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("Control individuals")
p3_cor_ibd_DA_CD

p4_cor_blInd_DA_CD<-ggplot(MGScor_blInd_DA_gat%>%filter(comparison=="CD vs. control"),aes(Direction,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("Individuals blocked")
p4_cor_blInd_DA_CD

p4_cor_all_DAibd_all_sigs_CD<-plot_grid(p1_cor_all_DA_CD+theme(legend.position = "none", axis.title = element_text(size=11), title = element_text(size=8)),
                                     p2_cor_ibd_DA_CD+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p3_cor_ibd_DA_CD+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p4_cor_blInd_DA_CD+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     nrow=1, rel_widths = c(1.2,1,1,1))
p4_cor_all_DAibd_all_sigs_CD
```

```{r}
# UC vs controls
p1_cor_all_DA_UC<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE%>%filter(comparison=="UC vs. control"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect\nsize (mean TE) UC-controls") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("All individuals")
p1_cor_all_DA_UC

p2_cor_ibd_DA_UC<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%filter(comparison=="UC vs. control"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("IBD individuals")
p2_cor_ibd_DA_UC

p3_cor_ibd_DA_UC<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%filter(comparison=="UC vs. control"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("Control individuals")
p3_cor_ibd_DA_UC

p4_cor_blInd_DA_UC<-ggplot(MGScor_blInd_DA_gat%>%filter(comparison=="UC vs. control"),aes(Direction,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("Individuals blocked")
p4_cor_blInd_DA_UC

p4_cor_all_DAibd_all_sigs_UC<-plot_grid(p1_cor_all_DA_UC+theme(legend.position = "none", axis.title = element_text(size=11), title = element_text(size=8)),
                                     p2_cor_ibd_DA_UC+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p3_cor_ibd_DA_UC+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p4_cor_blInd_DA_UC+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     nrow=1, rel_widths = c(1.2,1,1,1))
p4_cor_all_DAibd_all_sigs_UC
```

```{r}
# UC vs controls
p1_cor_all_DA_CDUC<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE%>%filter(comparison=="CD vs. UC"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect\nsize (mean TE) CD-UC") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("All individuals")
p1_cor_all_DA_CDUC

p2_cor_ibd_DA_CDUC<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_IBD%>%filter(comparison=="CD vs. UC"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("IBD individuals")
p2_cor_ibd_DA_CDUC

p3_cor_ibd_DA_CDUC<-ggplot(df_cor_all_DAibd_meanRhoVSmeanTE_CTRL%>%filter(comparison=="CD vs. UC"),aes(meanRho,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("Control individuals")
p3_cor_ibd_DA_CDUC

p4_cor_blInd_DA_CDUC<-ggplot(MGScor_blInd_DA_gat%>%filter(comparison=="CD vs. UC"),aes(Direction,meanTE))+
    geom_hline(yintercept = 0, linetype=2, color="grey80") +
    geom_vline(xintercept = 0, linetype=2, color="grey80") +
    #geom_smooth(method="lm", se = FALSE, color="grey70", size=1)+
    geom_point(size=1, alpha=0.7, aes(color=Phylum)) +
    #facet_wrap(.~comparison, scales = "free_x") +
    ylab("Mean differential abundance effect size (mean TE)") +
    theme_bw()+
    scale_x_reverse()+
    scale_color_manual(values=phy.col)+
    theme_bw()+
    theme(panel.grid = element_blank())+
  ggtitle("Individuals blocked")
p4_cor_blInd_DA_CDUC

p4_cor_all_DAibd_all_sigs_CDUC<-plot_grid(p1_cor_all_DA_CDUC+theme(legend.position = "none", axis.title = element_text(size=11), title = element_text(size=8)),
                                     p2_cor_ibd_DA_CDUC+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p3_cor_ibd_DA_CDUC+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     p4_cor_blInd_DA_CDUC+theme(legend.position = "none",  axis.title.x = element_text(size=11), axis.title.y = element_blank(), title = element_text(size=8)),
                                     nrow=1, rel_widths = c(1.2,1,1,1))
p4_cor_all_DAibd_all_sigs_CDUC
```

```{r fig.height=10,fig.width=12}
p_suppl_cor_all_DAibd<-plot_grid(
  p4_cor_all_DAibd_all_sigs_CD,
  p4_cor_all_DAibd_all_sigs_UC,
  p4_cor_all_DAibd_all_sigs_CDUC,
  ncol=1,labels=c("A","B","C")
)
p_suppl_cor_all_DAibd
```

```{r}
ggsave(paste0(PATH,"suppl_corr_DAq0.1.pdf"), p_suppl_cor_all_DAibd, width=12, height=10)
ggsave(paste0(PATH,"suppl_corr_DAq0.1.png"), p_suppl_cor_all_DAibd, width=12, height=10)

```



```{r, fig.width=13, fig.height=11}

olp_text<-ggplot()+
  geom_text(aes(1,1),label="overlap taxa", size=3.5,color="black")+
  theme_classic()+
  theme(axis.text=element_blank(),
        axis.title=element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank())

MGSnum.p1<-plot_grid(NA,NA,p_DAoverlap_noIBD+theme(legend.position="left"),NA,
                     NA,NA,NA,NA,
                     DAsumtab.obj.tab,NA,plot_grid(NA,p_DAoverlap2_noIBD,
                                                   NA,NA,
                                                   NA,olp_text,ncol=2,rel_widths=c(1,1),rel_heights=c(5,-1.2,1.25)),NA,ncol=4, align = "vh", axis="tblr", rel_heights=c(1,-0.25,1.2), rel_widths=c(1.8,-0.6,1.2,0.1))
MGSnum.p1


TreeTab.p1<-plot_grid(yy,MGSnum.p1,ncol=1,rel_heights=c(3,1.2), labels=c("A","B Number and overlap of CD-\n and UC-associated species "),hjust = 0, label_x = 0.01)
CorTopMGS.p1<-plot_grid(DAmeans.topMGS.p3,p4_cor_all_DAibd_all_sigs_IBD+theme(legend.position = "none"),
                          ncol=1,rel_heights = c(1,0.4), align = "v",axis = "lr", labels=c("C","D"),label_x = -0.02)

TreeTopMGS.p1<-plot_grid(TreeTab.p1,CorTopMGS.p1,ncol=2,rel_widths = c(1,1.2), align = "h",axis = "t")
TreeTopMGS.p2<-plot_grid(TreeTopMGS.p1,treelegend, ncol=1, rel_heights = c(7,1))
TreeTopMGS.p2

ggsave(paste0(PATH,"Fig2_DAq0.1.pdf"), TreeTopMGS.p2, width=13, height=11)
ggsave(paste0(PATH,"Fig2_DAq0.1.png"), TreeTopMGS.p2, width=14, height=11)
```

Export top MGS shown in fig

```{r}
saveRDS(DAmeans.topMGS.tax,paste0(PATHanalNov2023,"Downstream/Results/MGS.toptax_DAFigq0.1.rds"))
```